from fastapi import FastAPI, Request, HTTPException, status, Depends, Form
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse, Response, StreamingResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from schemas import PostCreate, PostResponse, UserResponse, UserCreate, QuestionResponse,QuestionCreate, Compass, CompassResponse
import json
from typing import Annotated
from sqlalchemy import select
from sqlalchemy.orm import Session
import models
from database import Base, engine, get_db
import requests
from google import genai
from dotenv import load_dotenv
from google import genai
import time
from google.genai import types
import pandas as pd
import plotly.express as px
import pydantic
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import io  # Ensure io is imported for BytesIO
from io import BytesIO, StringIO
from reportlab.platypus import SimpleDocTemplate, Image, Paragraph, Spacer
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from svglib.svglib import svg2rlg
from reportlab.platypus.flowables import ImageAndFlowables
from reportlab.lib.units import inch    
from reportlab.platypus import HRFlowable

app=FastAPI()

Sample_Response = {
  "philosophical_compass": {
    "individualism_collectivism": {
      "score": 50,
      "label": "Balanced / Communitarian",
      "evidence": "The author strikes a precise middle ground, arguing that while individual rights are vital, they are meaningless without a stable social contract. The text balances phrases like 'personal autonomy' directly with 'civic responsibility' throughout the critique."
    },
    "rationalism_irrationalism": {
      "score": 95,
      "label": "Strict Rationalist",
      "evidence": "The argument is built entirely on mathematical modeling and formal deductive logic. The author dismisses any emotional appeals as 'cognitive noise' and demands that all policy decisions be rooted strictly in peer-reviewed empirical data."
    },
    "universalism_relativism": {
      "score": 55,
      "label": "Contextual Universalist",
      "evidence": "The essay argues that while basic human rights are universal, the expression and execution of those rights must adapt to local customs. It attempts to bridge the gap by stating 'the core values are absolute, but the cultural lenses vary.'"
    },
    "determinism_free_will": {
      "score": 50,
      "label": "Compatibilist",
      "evidence": "The text explicitly argues that free will and determinism can coexist. It states that while our environment and genetics heavily constrain our available options, we still retain the conscious agency to choose our path among those limitations."
    },
    "overall_summary": "This essay presents a profound spiritual and ethical philosophy centered on interconnectedness and altruistic love. The author argues that true individual fulfillment ('becoming All') is achieved not through isolation but by consciously transcending egoistic boundaries and integrating into a 'universal whole.' Love is depicted as the primary mechanism for this transformation, shifting one's life focus from self to other and revealing the 'absolute central significance' inherent in every individual. Key themes include the transcendence of ego, the transformative power of love, universal human significance, and the essential role of community in individual actualization. The closest philosophical traditions include certain forms of Communitarianism (especially in its spiritual dimensions), Personalism, and potentially Eastern philosophies emphasizing interconnectedness (e.g., some aspects of Mahayana Buddhism or Vedantic thought). The strong emphasis on love and unity also resonates with the philosophies of Russian religious thinkers like Vladimir Solovyov. This analysis is generated by an AI based on the provided text and established philosophical frameworks. It aims to offer an objective interpretation and categorization of the essay's core ideas."

  }
}



data_container = {
"left_var": ['Indiviualism', 'Rationalism', 'Universalism', 'Determinism'],
"right_var": ['Collectivism', 'Irrationalism', 'Relativism', 'Free will'],
"right_scores": [],
"left_scores": [],
'label_list': [],
'evidence_list': []
}

for k, v in Sample_Response["philosophical_compass"].items():
    if isinstance(v, str):
        continue
    if isinstance(v, dict) and "score" in v:
        data_container["right_scores"].append(v["score"])
        new_val = (100 - v["score"])
        data_container["left_scores"].append(new_val)
        data_container['label_list'].append(v['label'])
        data_container["evidence_list"].append(v['evidence'])



df = pd.DataFrame(data_container)
fig = go.Figure()
combined_var = zip(df['left_var'],df['right_var'])


df['combined']=[f'{left} - {right}' for left, right in combined_var]

fig.add_trace(go.Bar(
    y=df["combined"],
    x=-df["left_scores"],
    orientation="h",
    name="Left",
    customdata=df[["left_scores", 'left_var', 'label_list', 'evidence_list']],
    hovertemplate=("%{customdata[1]}: %{customdata[0]} <br>"+
                   "label: %{customdata[2]}<br>"+
                   "evidence: %{customdata[3]}<br>"+
                    "<extra></extra>"),
    marker_color="#FB7185"
))

fig.add_trace(go.Bar(
    y=df["combined"],
    x=df["right_scores"],
    orientation="h",
    name="Right",
    customdata=df[['right_var', 'right_scores']],
    hovertemplate="%{customdata[0]}: %{customdata[1]}<extra></extra>",
    marker_color="#3B82F6"
))

fig.add_vline(
    x=0,
    line_width=3,
    line_color="#333333"
)

fig.update_layout(
    barmode="relative",
    title=dict(
        text='Philosophical Compass',
        x=0.5,
        xanchor='center',
        font=dict(size=24, color='#0d6efd', family='Arial'),
    ),
    xaxis_title="Score",
    yaxis_title="Category",
    yaxis_autorange="reversed",
    showlegend=False,
    plot_bgcolor="white",
    paper_bgcolor="white"
    
)
img_plot = fig.to_image(format="svg", width=700, height=400).decode("utf-8")



image_buffer = io.StringIO(img_plot)
img_flowable=svg2rlg(image_buffer)

doc=SimpleDocTemplate('output.pdf', pagesize=letter, leftMargin= 0.5*inch, rightMargin=0.5*inch, topMargin=0.75*inch, bottomMargin=0.2*inch)
story= []



styles=getSampleStyleSheet()

title_style = ParagraphStyle(
    'DocTitle',
    parent=styles['Normal'],
    fontName='Helvetica-Bold',
    fontSize=24,
    leading=28,                  
    alignment=1,                 
    textColor=colors.HexColor("#000000"),
    spaceAfter=16            
)

title_p = Paragraph("ANALYSIS", title_style)

custom_style = ParagraphStyle(
    'CustomStyle',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontSize=11,
    leading=16,
    textColor=colors.HexColor("#333333"),
    spaceAfter=12
)
p=Paragraph(Sample_Response["philosophical_compass"]["overall_summary"], custom_style)


evi_lab_style = ParagraphStyle(
    'CustomStyle',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontSize=10,
    leading=16,
    textColor=colors.HexColor('#111111'),
    spaceAfter=5
)

blank_style = ParagraphStyle(
    'CustomStyle',
    parent=styles['Normal'],
    spaceBefore=3,
    spaceAfter=10
)

evi_style = ParagraphStyle(
    'CustomStyle',
    parent=styles['Normal'],
    fontName='Helvetica-bold',
    fontSize=14,

    textColor=colors.HexColor('#111111'),
    spaceAfter=6
)

disclaimer_style =ParagraphStyle(
    'CustomStyle',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontsize = 14,
    leading=16,
    textColor=colors.HexColor("#000000"),
    spaceAfter=2
)


custom_style1= ParagraphStyle(
    'CustomStyle',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontsize = 8,
    leading=8*1.4,
    textColor=colors.HexColor("#000000"),
    spaceAfter=2
)

blank_space = Paragraph('', blank_style)
p_date=Paragraph('Date: 2026-07-10 13:53:51.351026+07:00', custom_style1)
p_session=Paragraph('Session ID: 0a9b251206342cfecebac5a92738d79d8e2b97a950d19c96308940e58090f7e5', custom_style1)

story.append(title_p)
story.append(HRFlowable(
    width="100%",           # Span across the entire printable page width
    thickness=1.5,          # Line weight in points
    color="#000000",     # Match the title color
    spaceBefore=5,          # Gap above the line
    spaceAfter=15,          # Gap below the line (before subtitle)
    hAlign='CENTER'
))
for k1, v1 in Sample_Response["philosophical_compass"].items():
    if isinstance(v1, str):
        continue
    if isinstance(v1,dict):
        lab_p=Paragraph(v1['label'], evi_style)
        evi_p=Paragraph(v1['evidence'], evi_lab_style)
        story.append(lab_p)
        story.append(evi_p)
    story.append(blank_space)
story.append(img_flowable)
story.append(p_date)
story.append(p_session)
story.append(Paragraph(
    "<i><b>AI Disclosure:</b> This report was generated with AI assistance. "
    "Please verify critical data points before making decisions.</i>", 
    disclaimer_style
))
story.append(Spacer(1,15))

doc.build(story)





    



    


        
        

